// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Web app (Flutter `web` target). Re-run `flutterfire configure` if keys rotate.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_8n15doTZqF63sp_jkXe6rkUUaW6O9-Q',
    appId: '1:679019957650:web:d4764847ca3519fc47c54b',
    messagingSenderId: '679019957650',
    projectId: 'family-super-app-3bf1c',
    authDomain: 'family-super-app-3bf1c.firebaseapp.com',
    storageBucket: 'family-super-app-3bf1c.firebasestorage.app',
    measurementId: 'G-MFSWBQJ8SL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYRNFp_j3a6D35P6P9ginD_AVx1tZ_wuw',
    appId: '1:679019957650:android:8c6cb7576949211947c54b',
    messagingSenderId: '679019957650',
    projectId: 'family-super-app-3bf1c',
    storageBucket: 'family-super-app-3bf1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8rp9iumph9nXh2gdxVv_ot1zN-6stT0k',
    appId: '1:679019957650:ios:9721a384af42d4f347c54b',
    messagingSenderId: '679019957650',
    projectId: 'family-super-app-3bf1c',
    storageBucket: 'family-super-app-3bf1c.firebasestorage.app',
    iosBundleId: 'com.family.superapp',
  );
}
